//Bodhi first joining you.
IF
	True()
THEN
	RESPONSE #100
	CutSceneId(Player1)
	SetInterrupt(FALSE)
	FadeToColor([20.0],0)
	CreateCreatureObject("YFBodhi","c6Bodhi",0,0,0)
	SetGlobal("YFBodhiHasSoul","GLOBAL",1) 
	SetGlobal("YFBodhiJoinsParty","GLOBAL",1)  
	ActionOverride("c6Bodhi",Kill("c6Bodhi"))
	Wait(1)
	ActionOverride("c6Bodhi",DestroySelf())
	FadeFromColor([20.0],0)
	ActionOverride("YFBodhi",StartDialogNoSet(Player1))
END

